### R info of packages in files
```{r, include=FALSE}
hooks = knitr::knit_hooks$get()
hook_foldable = function(type) {
  force(type)
  function(x, options) {
    res = hooks[[type]](x, options)
    
    if (isFALSE(options[[paste0("fold.", type)]])) return(res)
    
    paste0(
      "<details><summary>", type, "</summary>\n\n",
      res,
      "\n\n</details>"
    )
  }
}
knitr::knit_hooks$set(
  output = hook_foldable("output"),
  plot = hook_foldable("plot")
)
```

#### R global session
```{r}
infos <- devtools::session_info()
infos
```

#### R packages
```{r}
infos[2]$packages$package |>
  purrr::map(citation) |>
  print(style = "text")
```


#### Extracting data
```{r}
NCmisc::list.functions.in.file(filename = "1_extracting_specific_dates_listeNoms.R")
```

#### Manual editing data
```{r}
NCmisc::list.functions.in.file(filename = "3_manual_editing.R")
```

#### Data critics
```{r}
NCmisc::list.functions.in.file(filename = "4_data_critics_and_output_version.R")
```

#### Data analysis
```{r}
NCmisc::list.functions.in.file(filename = "5_data_analysis.R")
```